### ISSUE TITLE
CorrelationId is not set in Log4Net

### ISSUE THREAD

**Issue by grzewal** [rebus-org/Rebus.Log4net#1]
Hi! 

I cannot seem to get Log4Net to log correlationId. I went throug the sources and there seem to be no trace of setting the correlation id to log4net ThreadContext or better yet LogicalThreadContext. 

Cheers

**Comment by mookid8000** [comment]
That's not how it's supposed to be... just a moment

**Comment by mookid8000** [comment]
Rebus.Log4Net 2.1.0 will automatically add a logical thread context `CorrelationId` property which can be used e.g. with a pattern like this:

```
%timestamp [%thread] %level %logger %property{CorrelationId} - %message%newline
```
